from rest_framework import generics
from django.shortcuts import render,redirect


from .models import Tutorial,Archive
from .serializers import TutorialSerializer,ArchiveSerializer
from .models import *
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger,InvalidPage
from django.contrib import messages
from django.http import HttpResponse
from datetime import datetime
import datetime


todaystr = datetime.date.today().strftime('%Y-%m-%d')
today = datetime.date.today()
class ListToTutorial(generics.ListCreateAPIView):
    queryset = Tutorial.objects.all()
    serializer_class = TutorialSerializer


class DetailToTutorial(generics.RetrieveUpdateDestroyAPIView):
    queryset = Tutorial.objects.all()
    serializer_class = TutorialSerializer


class ListToArchive(generics.ListCreateAPIView):
    queryset = Archive.objects.all()
    serializer_class = ArchiveSerializer


class DetailToArchive(generics.RetrieveUpdateDestroyAPIView):
    queryset = Archive.objects.all()
    serializer_class = ArchiveSerializer


def homepage(request):
    tutorial_series = TutorialSeries.objects.all()
    archives = Archive.objects.all()
    
    comments = Comment.objects.all()
    comment_count = comments.count

    print(tutorial_series)
    context = {"tutorial_series":tutorial_series,"archives":archives,"comments":comments,"comment_count":comment_count,"today":today}
    return render(request,'main/homepage.html',context)


def tutorial(request,pk):
    tutorial_series = TutorialSeries.objects.get(tutorial_series=pk)
 
    tutorial = tutorial_series.tutorial_set.all().order_by('id')
    
    paginator = Paginator(tutorial, 1)
    page = request.GET.get('page')
    tutorials = paginator.get_page(page)

    
    comments = Comment.objects.filter(tutorial=tutorial_series)
    
    comment_count = comments.count
    
    print('this is ',comments)
    
    n =datetime.datetime.now()

    


    context = {"tutorial":tutorial,"tutorial_series":tutorial_series, 'items': tutorials,"comments":comments,"comment_count":comment_count,"today":today,"n":n}
    return render(request,'main/tutorial.html',context)


def likePost(request):
    if request.method == 'GET':
            comment_id = request.GET['comment_id']
            likedpost = Comment.objects.get(pk=comment_id) #getting the liked posts
            m = Like(comment=likedpost) # Creating Like Object
            m.save()  # saving it to store in database
            
            l = Like.objects.all()
            print("l is " ,l)
            print("l is not " , l.count())
            return HttpResponse("Liked") # Sending an success response
    else:
            return HttpResponse("Request method is not a GET")


def dislikePost(request):
    if request.method == 'GET':
            comment_id = request.GET['comment_id']
            dislikedpost = Comment.objects.get(pk=comment_id) #getting the liked posts
            m = Dislike(comment=dislikedpost) # Creating Like Object
            m.save()  # saving it to store in database
            l = Dislike.objects.all()
            print(l.count)
            return HttpResponse("Disliked!") # Sending an success response
    else:
            return HttpResponse("Request method is not a GET")

def subscribe(request):
    
    if request.method == 'GET':
            email_given = request.GET['email']
            if Subscription.objects.filter(email=email_given).exists():
                return HttpResponse("You are already subscribed")
            else:
                m = Subscription(email=email_given) # Creating Like Object
                m.save()  # saving it to store in database


                import smtplib

                # import the corresponding modules
                from email import encoders
                from email.mime.base import MIMEBase
                from email.mime.image import MIMEImage
                from email.mime.multipart import MIMEMultipart
                from email.mime.text import MIMEText


                smtp_server = "smtp.gmail.com"
                login = "devngecu@gmail.com" # paste your login generated by Mailtrap
                password = "MotherFucker21" # paste your password generated by Mailtrap

                subject = "DevNgecu Subscription"
                sender_email = "devngecu@gmail.com"
                receiver_email = [email_given,"devngecu@gmail.com"]

                
                message = MIMEMultipart()
                message["From"] = sender_email
                message["To"] = ", ".join(receiver_email) 
                message["Subject"] = subject
                body = "Thank you,for your generous comment.I am thrilled to have your support.Through your contributions I have been able to accomplish your demands and continue working towards improving other people's programming ideas. You truly make the difference for me, and I am extremely grateful! \n If you have specific questions about the tutorials, please don’t hesitate to contact me through whatsapp +25707583092."
                print(body)

                html = """\

    <!doctype html>
    <html lang="en">
    <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Dev Ngecu</title>

    <style>
        @media screen and (max-width: 600px) {
            .remove-flex-mobile {
                display: block !important;
            }
            .remove-flex-basis-mobile {
                flex-basis: unset !important;
                padding-left: 0 !important;
            }
            .display-grid-mobile {
                grid-template-columns: 1fr !important;
            }
            .reminders-list {
                padding-left: 15px !important;
                margin-top: 10px !important;
            }
            .reminders-table td {
                float: unset !important;
                display: block !important;
                width: unset !important;
                margin-left: 0 !important;
            }
            .second-item-order {
                flex-direction: column !important;
                align-items: flex-start !important;
            }
            .flex-order {
                order: 2 !important;
            }
            .list-header {
                padding-top: 20px !important;
            }
            .navigation-footer {
                text-align: center !important;
            }
            .navigation-footer li {
                display: list-item !important;
                padding: 10px 0 !important;
            }
            .social-media img {
                width: 30px !important;
            }
            .social-media a {
                padding: 0 3px 0 0 !important;
            }
            .social-media a:last-of-type {
                padding-right: 0 !important;
            }
        }
    </style>
    </head>
    <body style="margin:0;">
    <table style="border: none; margin: 0 auto ; padding: 0;">
    <tr>
        <td style="padding: 0; background-color: #FFFFFF;">

            <div style="max-width: 600px; min-width: 200px; font-family: 'Arial', sans-serif; font-size: 16px; background-color: #FFFFFF; line-height: 1.4; color: #4A4A4A; border: 1px solid #DFDFDF; border-radius: 10px; overflow: hidden;">

                <div style="background-color: #e8c547; height: 60px;">
                </div>

                <header style="text-align: center;">
                    <h1 style="font-size: 58px;color: #30323d; background: #FFFFFF; margin-top: 30px; margin-bottom: 0; text-transform: uppercase;">ASANTE SANA</h1>
                    <p style="margin: 0; padding-bottom: 30px; font-size:18px;">THANK YOU</p>
                </header>

                <div style="padding: 0 20px;">
                    <p>
                       """ +str(email_given) + """  Thank you for your generous subscription dated .I am thrilled to have your support.Through your contributions I will been able to accomplish your wishes and demands and continue working towards improving other people's programming ideas and skills. You truly make the difference for alot of programmers, and I am extremely grateful!
                            <br> <br>
                            If you have specific questions about the tutorials, please don’t hesitate to contact me,stating your name,through whatsapp +25707583092.
                            <br> <br>
                            Sincerely,
                            <br><br>
                            Dev Ngecu
                    
                    </p>
                </div>

        


            <!-- START FOOTER -->
            <div class="footer" style="clear: both; Margin-top: 10px; text-align: center; width: 100%;">
                <table border="0" cellpadding="0" cellspacing="0" style="border-collapse: separate; mso-table-lspace: 0pt; mso-table-rspace: 0pt; width: 100%;">
                    <tr>
                        <td class="content-block" style="font-family: sans-serif; vertical-align: top; padding-bottom: 10px; padding-top: 10px; font-size: 12px; color: #999999; text-align: center;">
                                <span class="apple-link"
                                        style="color: #999999; font-size: 12px; text-align: center;">From my bed to
                                you in bed somewhere in the karantini. I'm this bored sigh</span>
                            <br> Don't like these emails? <a
                                    style="text-decoration: underline; color: #999999;
                                                                    font-size: 12px; text-align: center;">You are stuck with them </a>.
                        </td>
                    </tr>
                    <tr>
                        <td class="content-block powered-by" style="font-family: sans-serif; vertical-align: top; padding-bottom: 10px; padding-top: 10px; font-size: 12px; color: #999999; text-align: center;">
                            Powered by <a href="http://htmlemail.io" style="color: #999999; font-size: 12px;
                                text-align: center; text-decoration: none;">My ability to adapt code to fit my needs</a>.
                        </td>
                    </tr>
                </table>
            </div>
            <!-- END FOOTER -->
        </td>
    </tr>
    </table>
    </body>
    </html>

                """

                part2 = MIMEText(html, "html")



                # Add attachment to your message and convert it to string
                message.attach(part2)

                # We assume that the image file is in the same directory that you run your Python script from
                

            

                text = message.as_string()

                # send your email
                with smtplib.SMTP("smtp.gmail.com",587) as server:
                    print(sender_email)
                    server.ehlo()
                    server.starttls()
                    server.login('devngecu@gmail.com', password)
                    server.sendmail(
                        sender_email, receiver_email, text
                    )
                    server.quit()


                return HttpResponse("THANK YOU FOR YOUR SUBSCRIPTION!") # Sending an success response
    else:
                return HttpResponse("Request method is not a GET")




def comment(request,pk):
    tutorial_series = TutorialSeries.objects.get(tutorial_series=pk)

    
    if request.method == 'GET':
            commentor_name = request.GET['name']
            commentor_email = request.GET['email']
            comment = request.GET['comment']
            
            

            m = Comment(tutorial=tutorial_series,name=commentor_name,email=commentor_email,body=comment) # Creating Like Object
            m.save()  # saving it to store in database

            import smtplib

            # import the corresponding modules
            from email import encoders
            from email.mime.base import MIMEBase
            from email.mime.image import MIMEImage
            from email.mime.multipart import MIMEMultipart
            from email.mime.text import MIMEText


            smtp_server = "smtp.gmail.com"
            login = "devngecu@gmail.com" # paste your login generated by Mailtrap
            password = "MotherFucker21" # paste your password generated by Mailtrap

            subject = "DevNgecu Subscription"
            sender_email = "devngecu@gmail.com"
            receiver_email = [commentor_email, "devngecu@gmail.com"]

            
            message = MIMEMultipart()
            message["From"] = sender_email
            message["To"] = ", ".join(receiver_email) 
            message["Subject"] = subject
            body = "Thank you for your generous comment.I am thrilled to have your support.Through your contributions I have been able to accomplish your demands and continue working towards improving other people's programming ideas. You truly make the difference for me, and I am extremely grateful! \n If you have specific questions about the tutorials, please don’t hesitate to contact me through whatsapp +25707583092."
            print(body)

            html = """\

            <!doctype html>
            <html lang="en">
            <head>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1">
            <meta http-equiv="X-UA-Compatible" content="IE=edge">
            <title>Dev Ngecu</title>

            <style>
                @media screen and (max-width: 600px) {
                    .remove-flex-mobile {
                        display: block !important;
                    }
                    .remove-flex-basis-mobile {
                        flex-basis: unset !important;
                        padding-left: 0 !important;
                    }
                    .display-grid-mobile {
                        grid-template-columns: 1fr !important;
                    }
                    .reminders-list {
                        padding-left: 15px !important;
                        margin-top: 10px !important;
                    }
                    .reminders-table td {
                        float: unset !important;
                        display: block !important;
                        width: unset !important;
                        margin-left: 0 !important;
                    }
                    .second-item-order {
                        flex-direction: column !important;
                        align-items: flex-start !important;
                    }
                    .flex-order {
                        order: 2 !important;
                    }
                    .list-header {
                        padding-top: 20px !important;
                    }
                    .navigation-footer {
                        text-align: center !important;
                    }
                    .navigation-footer li {
                        display: list-item !important;
                        padding: 10px 0 !important;
                    }
                    .social-media img {
                        width: 30px !important;
                    }
                    .social-media a {
                        padding: 0 3px 0 0 !important;
                    }
                    .social-media a:last-of-type {
                        padding-right: 0 !important;
                    }
                }
            </style>
            </head>
            <body style="margin:0;">
            <table style="border: none; margin: 0 auto ; padding: 0;">
            <tr>
                <td style="padding: 0; background-color: #FFFFFF;">

                    <div style="max-width: 600px; min-width: 200px; font-family: 'Arial', sans-serif; font-size: 16px; background-color: #FFFFFF; line-height: 1.4; color: #4A4A4A; border: 1px solid #DFDFDF; border-radius: 10px; overflow: hidden;">

                        <div style="background-color: #e8c547; height: 60px;">
                        </div>

                        <header style="text-align: center;">
                            <h1 style="font-size: 58px;color: #30323d; background: #FFFFFF; margin-top: 30px; margin-bottom: 0; text-transform: uppercase;">ASANTE SANA</h1>
                            <p style="margin: 0; padding-bottom: 30px; font-size:18px;">THANK YOU</p>
                        </header>

                        <div style="padding: 0 20px;">
                            <p>
                            Dear  <b> """ +str(commentor_name) + """ </b> <br>
                                Thank you for your generous comment dated  <b> """ +str(todaystr) + """ </b>.I am thrilled to have your support.Through your contributions I will been able to accomplish your wishes and demands and continue working towards improving other people's programming ideas and skills. You truly make the difference for alot of programmers, and I am extremely grateful! 
                                    <br> <br>
                                    If you have specific questions about the tutorials, please don’t hesitate to contact me,stating your name,through whatsapp +25707583092.
                                    <br> <br>
                                    Sincerely,
                                    <br><br>
                                    Dev Ngecu
                            
                            </p>
                        </div>

                


                    <!-- START FOOTER -->
                    <div class="footer" style="clear: both; Margin-top: 10px; text-align: center; width: 100%;">
                        <table border="0" cellpadding="0" cellspacing="0" style="border-collapse: separate; mso-table-lspace: 0pt; mso-table-rspace: 0pt; width: 100%;">
                            <tr>
                                <td class="content-block" style="font-family: sans-serif; vertical-align: top; padding-bottom: 10px; padding-top: 10px; font-size: 12px; color: #999999; text-align: center;">
                                        <span class="apple-link"
                                                style="color: #999999; font-size: 12px; text-align: center;">From my bed to
                                        you in bed somewhere in the karantini. I'm this bored sigh</span>
                                    <br> Don't like these emails? <a
                                            style="text-decoration: underline; color: #999999;
                                                                            font-size: 12px; text-align: center;">You are stuck with them </a>.
                                </td>
                            </tr>
                            <tr>
                                <td class="content-block powered-by" style="font-family: sans-serif; vertical-align: top; padding-bottom: 10px; padding-top: 10px; font-size: 12px; color: #999999; text-align: center;">
                                    Powered by <a href="http://htmlemail.io" style="color: #999999; font-size: 12px;
                                        text-align: center; text-decoration: none;">My ability to adapt code to fit my needs</a>.
                                </td>
                            </tr>
                        </table>
                    </div>
                    <!-- END FOOTER -->
                </td>
            </tr>
            </table>
            </body>
            </html>

            """

            part2 = MIMEText(html, "html")



            # Add attachment to your message and convert it to string
            message.attach(part2)

            # We assume that the image file is in the same directory that you run your Python script from
            

        

            text = message.as_string()

            # send your email
            with smtplib.SMTP("smtp.gmail.com",587) as server:
                print(sender_email)
                server.ehlo()
                server.starttls()
                server.login('devngecu@gmail.com', password)
                server.sendmail(
                    sender_email, receiver_email, text
                )
                server.quit()

            return HttpResponse("THANK YOU FOR YOUR Comment") # Sending an success response


    else:
                return HttpResponse("Request method is not a GET")