# Generated by Django 3.0.7 on 2020-06-07 09:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archive_title', models.CharField(max_length=200)),
                ('archive_description', models.CharField(max_length=200)),
                ('archive_url', models.CharField(max_length=200)),
                ('demo', models.BooleanField(default=False)),
                ('archive_published', models.DateTimeField(default=datetime.datetime(2020, 6, 7, 12, 51, 23, 635626), verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tutorial_title', models.CharField(max_length=200)),
                ('tutorial_content', models.TextField()),
                ('tutorial_published', models.DateTimeField(default=datetime.datetime(2020, 6, 7, 12, 51, 23, 635177), verbose_name='date published')),
                ('image', models.ImageField(upload_to='photos/%Y/%m/%d')),
            ],
        ),
    ]
