# Generated by Django 3.0.7 on 2020-06-09 10:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200609_0554'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorialseries',
            name='source_code',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='archive',
            name='archive_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 9, 13, 30, 14, 929034), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 9, 13, 30, 14, 927945), verbose_name='date published'),
        ),
    ]
