# Generated by Django 3.0.7 on 2020-06-09 11:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200609_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archive',
            name='archive_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 9, 14, 8, 5, 991764), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 9, 14, 8, 5, 991134), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='tutorialseries',
            name='source_code',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tutorialseries',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
