# Generated by Django 3.0.7 on 2020-06-22 18:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20200622_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archive',
            name='archive_published',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 6, 22, 21, 5, 47, 860545), null=True, verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 6, 22, 21, 5, 47, 859932), null=True, verbose_name='date published'),
        ),
    ]
