# Generated by Django 3.0.7 on 2020-06-23 10:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20200622_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archive',
            name='archive_published',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 6, 23, 13, 23, 52, 723729), null=True, verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 6, 23, 13, 23, 52, 723159), null=True, verbose_name='date published'),
        ),
    ]
