# Generated by Django 3.0.7 on 2020-06-24 08:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20200624_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archive',
            name='archive_published',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 6, 24, 11, 55, 2, 930684), null=True, verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 6, 24, 11, 55, 2, 930106), null=True, verbose_name='date published'),
        ),
    ]
