# Generated by Django 3.0.7 on 2020-06-24 11:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20200624_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archive',
            name='archive_published',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 6, 24, 14, 18, 47, 433410), null=True, verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='archive',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 6, 24, 14, 18, 47, 432787), null=True, verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='tutorialseries',
            name='series_image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
